environment:
  name: test-node-cd-prod
  identifier: test_node_cd_prod
  description: "Production Environment"
  tags: {}
  type: Production
  orgIdentifier: default
  projectIdentifier: harnessProject
  variables: []

