environment:
  name: test-node-cd-environment
  identifier: test_node_cd_environment
  description: ""
  tags: {}
  type: Production
  orgIdentifier: default
  projectIdentifier: harnessProject
  variables: []
 